Update_happy-new-year.sh
subins2000/new-year-bash pull request #1
Opened 2023-12-26 10:22 UTC by arnabmukho

2023-12-26 15:22 UTC, tachyons commented
🥇

2023-12-26 15:29 UTC, balasankarc commented
+1

2023-12-26 16:10 UTC, vivekkj123 commented
LGTM 👀

2023-12-27 06:41 UTC, subins2000 commented
@arnabmukho Hi, what is the point of this PR? Why change the name?

2023-12-27 06:42 UTC, tachyons requested changes

2023-12-27 06:42 UTC, tachyons commented on happy-new-year.sh
> +name='Arnab :)'
```suggestion
name='Arnab 😀'
```

2023-12-27 06:44 UTC, closed without merging